Repository prgrms-web-devcourse-final-project/WEB1_1_Postman_FE, pull requests merged in 2024-12, with the labels that each got.

#140 feat : 지도 위치 검색 레이아웃 개발 완료
  src/components/MapPage/Maplibre/Maplibre.stories.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.stories.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
Labels: ✨feature

#145 feat : 라벨 , 키워드 선택 컴포넌트 개발
  .pnp.cjs
  .storybook/preview.jsx
  package.json
  src/App.tsx
  src/components/Common/BottleLetter/Bottle/Bottle.stories.tsx
  src/components/Common/BottleLetter/Bottle/Bottle.tsx
  src/components/Common/BottleLetter/Label/Label.tsx
  src/components/Common/ItemSlider/ItemSlider.tsx
  src/components/Common/KeywordToggleButton/KeywordToggleButton.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/TopBar/TopBar.stories.tsx
  src/components/Common/TopBar/TopBar.tsx
  src/components/Letter/AnimationBottle/AnimationBottle.stories.tsx
  src/components/Letter/AnimationBottle/AnimationBottle.tsx
  src/components/Letter/CreateButton/CreateButton.stories.tsx
  src/components/Letter/CreateButton/CreateButton.tsx
  src/components/Letter/KeywordList/KeywordList.tsx
  src/components/Letter/LabelList/LabelList.tsx
  src/components/Letter/Post/PostLetterForm.stories.tsx
  src/components/Letter/Post/PostLetterForm.tsx
  src/components/Letter/SelectItem/SelectItem.stories.tsx
  src/components/Letter/SelectItem/SelectItem.tsx
  src/pages/Letter/Create/CreateLetterPage.tsx
  src/pages/Letter/SelectItem/SelectItemPage.tsx
  src/pages/User/Register/RegisterPage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/stores/stories/Button.stories.ts
  src/stores/stories/Button.tsx
  src/stores/stories/Configure.mdx
  src/stores/stories/Header.stories.ts
  src/stores/stories/Header.tsx
  src/stores/stories/Page.stories.ts
  src/stores/stories/Page.tsx
  src/stores/stories/assets/accessibility.png
  src/stores/stories/assets/accessibility.svg
  src/stores/stories/assets/addon-library.png
  src/stores/stories/assets/assets.png
  src/stores/stories/assets/avif-test-image.avif
  src/stores/stories/assets/context.png
  src/stores/stories/assets/discord.svg
  src/stores/stories/assets/docs.png
  src/stores/stories/assets/figma-plugin.png
  src/stores/stories/assets/github.svg
  src/stores/stories/assets/share.png
  src/stores/stories/assets/styling.png
  src/stores/stories/assets/testing.png
  src/stores/stories/assets/theming.png
  src/stores/stories/assets/tutorials.svg
  src/stores/stories/assets/youtube.svg
  src/stores/stories/button.css
  src/stores/stories/header.css
  src/stores/stories/page.css
  src/types/keyword.ts
  src/types/label.ts
  tailwind.config.js
  yarn.lock
Labels: ✨feature

#148 feat : 회원가입 페이지 개발 2차 (닉네임 중복&제출 기능 추가)
  .pnp.cjs
  src/components/Common/Input/ConfirmPasswordInput.tsx
  src/components/Common/Input/Input.tsx
  src/components/Common/Input/NicknameInput.tsx
  src/components/Common/Input/PasswordInput.tsx
  src/components/Common/Toast/Toast.tsx
  src/components/Common/ToastContainer/ToastContainer.tsx
  src/components/RegisterPage/ConfirmPasswordInput.tsx
  src/components/RegisterPage/EmailSection.tsx
  src/components/RegisterPage/EmailVerificationInput.tsx
  src/components/RegisterPage/NicknameSection.tsx
  src/components/RegisterPage/PasswordSection.tsx
  src/constants/authInputValidation.ts
  src/hooks/useDebounde.ts
  src/hooks/useRegisterForm.tsx
  src/mocks/handlers/RegisterHandler.ts
  src/pages/User/Register/RegisterPage.tsx
  src/service/auth/checkNickname.ts
  src/service/auth/index.ts
  src/service/auth/register.ts
Labels: ✨feature, ♻️ refactor

#158 feat : textarea 너비에 따른 줄 간격 조정
  .pnp.cjs
  src/components/Common/TextArea/TextArea.tsx
Labels: ✨feature, 💧우선 순위 중

#154 feat : 라벨 뽑기 페이지 라우팅 및 레이아웃 개발
  src/components/Common/Banner/LabelLotteryBanner.tsx
  src/components/Common/BannerContainer/BannerContainer.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Label/Lottery/LabelLotteryPage.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨feature

#159 feat : 답장 편지 컴포넌트 레이아웃 개발 완료
  src/components/LetterDetailPage/ReplyLetterDetail.tsx
Labels: ✨feature

#162 chore : 메인페이지 토글버튼 수정된 컴포넌트로 변경
  src/pages/Home/HomePage.tsx
Labels: ✏️chore

#163 160 feat 답장 편지 상세보기 페이지 레이아웃 개발 완료
  src/components/LetterDetailPage/ReplyList/ReplyList.stories.tsx
  src/components/LetterDetailPage/ReplyList/ReplyList.tsx
  src/pages/Home/HomePage.stories.tsx
  src/pages/Letter/Detail/LetterDetailPage.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.stories.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨feature

#167 166 feat 지도 편지 페이지 컴포넌트 수정 및 라우팅
  src/components/Common/DayCounter/DayCounter.stories.tsx
  src/components/Common/DayCounter/DayCounter.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.stories.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/NavigateContainer/NavigateContainer.stories.tsx
  src/components/MapPage/NavigateContainer/NavigateContainer.tsx
Labels: ✨feature

#165 style : globalstyle 설정
  .pnp.cjs
  package.json
  postcss.config.cjs
  postcss.config.js
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Letter/AnimationBottle/AnimationBottle.tsx
  src/components/MapPage/Maplibre/Maplibre.tsx
  src/index.css
  src/pages/Letter/Create/CreateLetterPage.tsx
  src/pages/Letter/SelectItem/SelectItemPage.tsx
  src/pages/Letter/Success/SuccessLetterPage.tsx
  src/pages/Map/MapExplorerPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨style

#168 feat : 알림페이지 개발 1차
  src/components/Common/NotificationBadge/NotificationBadge.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/NotificationPage/ClickableNotification.tsx
  src/components/NotificationPage/NotificationAppBar/NotificationAppBar.tsx
  src/components/NotificationPage/ReadNotificationContainer.tsx
  src/components/NotificationPage/UnReadNotificationContainer.tsx
  src/pages/Notification/NotificationPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨feature

#169 feat : 마이페이지 프로필 조회&수정 1차 완료
  public/ic_pen.svg
  public/ic_share_3.svg
  src/components/Common/Input/Input.tsx
  src/components/Common/ListItem/ListItem.tsx
  src/components/Common/MenuListItem/MenuListItem.tsx
  src/components/Common/ProfileImage/ProfileImage.tsx
  src/components/Common/SliderMenuContainer/SliderMenuContainer.tsx
  src/components/MyPage/IconMenuButton.tsx
  src/components/MyPage/MenuListSection.tsx
  src/components/MyPage/ProfileSection.tsx
  src/components/MyPage/RecordGridSection.tsx
  src/components/Profile/AccountInfoSection.tsx
  src/components/Profile/NicknameSection.tsx
  src/components/Profile/ProfileImageSection.tsx
  src/components/RegisterPage/NicknameSection.tsx
  src/hooks/useRegisterForm.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/userEditHandler.ts
  src/pages/User/MyPage/MyPage.stories.tsx
  src/pages/User/MyPage/MyPage.tsx
  src/pages/User/Profile/ProfilePage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/service/user/changeNickname.ts
  src/service/user/changeProfileImage.ts
  src/service/user/index.ts
  src/types/profileImage.ts
Labels: ✨feature

#173 fix : ListItem 스토리북 오류 수정
  src/components/Common/ListItem/ListItem.stories.tsx
Labels: 🐛 fix

#175 fix : NotificationBadge 스토리북 오류 수정
  src/components/Common/NotificationBadge/NotificationBadge.stories.tsx
Labels: 🐛 fix

#177 feat : 프로필 이미지 스토리북 오류 수정
  src/components/Common/ProfileImage/ProfileImage.stories.tsx
Labels: 🐛 fix

#170 164 feat 지도 편지 페이지 2차 개발
  .pnp.cjs
  src/components/HomePage/LetterContainer/LetterContainer.stories.tsx
  src/components/LetterDetailPage/MapLetterDetail.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.stories.tsx
  src/components/MapPage/Maplibre/Maplibre.tsx
  src/pages/Map/MapExplorerPage.stories.tsx
  src/pages/Map/MapExplorerPage.tsx
  src/stores/useSelectedLetterStore.tsx
  yarn.lock
Labels: ✨feature

#182 fix : index.ts 오류 수정
  src/pages/index.tsx
Labels: 🐛 fix

#186 feat : Logo 컴포넌트 생성 및 메인페이지 상단 로고, 알림버튼 개발
  public/logo.svg
  src/components/Common/LogoContainer/Logo.stories.tsx
  src/components/Common/LogoContainer/Logo.tsx
  src/components/Common/NotificationBadge/NotificationBadge.stories.tsx
  src/components/Common/NotificationBadge/NotificationBadge.tsx
  src/components/HomePage/TopButtonContainer/TopButtonContainer.stories.tsx
  src/components/HomePage/TopButtonContainer/TopButtonContainer.tsx
Labels: ✨feature

#190 feat : 지도 편지 페이지 SearchFullScreen 컴포넌트 레이아웃 개발 완료
  src/components/MapPage/SearchFullScreen/SearchFullScreen.stories.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/components/MapPage/SearchHistoryList/SearchHistoryList.tsx
Labels: ✨feature

#192 191 feat 지도 편지 페이지 검색창 포커스 시 searchfullscreen 표시
  src/components/MapPage/Maplibre/MaplibreWithSearch.stories.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/pages/Map/MapExplorerPage.tsx
Labels: ✨feature

#194 feat : 알림페이지 컴포넌트 생성
  src/components/HomePage/TopButtonContainer/TopButtonContainer.tsx
  src/components/NotificationPage/ClickableNotification.tsx
  src/components/NotificationPage/NotificationAppBar.tsx
  src/components/NotificationPage/NotificationAppBar/NotificationAppBar.tsx
  src/components/NotificationPage/NotificationContainer.tsx
  src/components/NotificationPage/NotificationItem.tsx
  src/components/NotificationPage/ReadNotificationContainer.tsx
  src/components/NotificationPage/UnReadNotificationContainer.tsx
  src/pages/Notification/NotificationPage.tsx
  src/types/notification.ts
Labels: ✨feature

#200 reafactor : 작성 로직 리펙토링 및 스타일 수정
  .pnp.cjs
  public/to_line.f4c129e6.svg
  public/편지지_샘플_6.png
  src/components/Common/ItemSlider/ItemSlider.tsx
  src/components/Common/SliderMenuContainer/SliderMenuContainer.tsx
  src/components/Common/TextArea/TextArea.tsx
  src/components/CreatLetterPage/Post/PostLetterForm.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/Letter/CreateButton/CreateButton.tsx
  src/components/Letter/Post/PostLetterForm.stories.tsx
  src/components/Letter/Post/PostLetterForm.tsx
  src/components/Letter/SelectItem/SelectItem.tsx
  src/components/Letter/SelectSlier/SelectSlider.tsx
  src/hooks/useLocalStorage.ts
  src/pages/Letter/Create/CreateLetterPage.tsx
  src/pages/Letter/SelectItem/SelectItemPage.tsx
Labels: ♻️ refactor, 🎨style

#198 feat : 로그인&회원가입 페이지 2차
  src/components/Common/Container/Container.tsx
  src/components/Common/Input/Input.tsx
  src/components/RegisterPage/EmailSection.tsx
  src/components/RegisterPage/NicknameSection.tsx
  src/components/RegisterPage/PasswordSection.tsx
  src/constants/authInputValidation.ts
  src/index.css
  src/mocks/index.ts
  src/pages/User/Login/LoginPage.tsx
  src/pages/User/Register/RegisterPage.tsx
  src/router.tsx
  src/service/api.ts
  src/service/auth/login.ts
  src/service/auth/refreshAccessToken.ts
  src/service/auth/tokenStorage.ts
  src/service/user/getUserInfo.ts
  src/stores/useUserStore.ts
  src/types/apiResponse.ts
Labels: ✨feature, 🎨style

#206 feat : 편지 작성 자동 저장 기능 추가
  src/components/Letter/Post/PostLetterForm.tsx
  src/hooks/useAutoSave.ts
Labels: ✨feature

#197 193 feat 지도 편지 페이지 검색 기능 개발
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/hooks/useNominatimSearch.ts
  src/main.tsx
  src/pages/Map/MapExplorerPage.tsx
Labels: ✨feature

#210 fix : 메인페이지 웰컴메시지 오류
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.tsx
  src/pages/Home/HomePage.tsx
Labels: 🐛 fix

#213 style : Toggle 컴포넌트 스타일 수정
  src/components/Common/Toggle/Toggle.tsx
Labels: 🎨style

#216 feat : 로그인&회원가입 (3차) 타입 수정 / 로직 분리
  src/pages/User/Login/LoginPage.tsx
  src/service/auth/login.ts
  src/service/auth/tokenStorage.ts
  src/service/user/getUserInfo.ts
  src/types/apiResponse.ts
  src/types/login.ts
Labels: 🐛 fix, ♻️ refactor

#215 209 feat 지도 편지 페이지 최근검색어 기능 개발
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/components/MapPage/SearchHistoryList/SearchHistoryList.tsx
  src/hooks/useNominatimSearch.ts
  src/pages/Map/MapExplorerPage.stories.tsx
  src/pages/Map/MapExplorerPage.tsx
Labels: ✨feature

#221 feat : 편지 작성 시 폭죽 터트리기
  .pnp.cjs
  package.json
  src/pages/Letter/Success/SuccessLetterPage.tsx
  yarn.lock
Labels: 🎨style

#222 style : 메인페이지 스타일 수정
  src/components/Common/KeywordToggleButton/KeywordToggleButton.tsx
  src/components/HomePage/BottomSheetContent/BottomSheetContent.tsx
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.tsx
  src/pages/Home/HomePage.tsx
Labels: 🎨style

#224 220 refactor 지도 편지 페이지 최근 검색어 기능 refactoring
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/hooks/useNominatimSearch.ts
  src/pages/Map/MapExplorerPage.tsx
  src/stores/useSearchStore.ts
Labels: ♻️ refactor

#225 refactor : 메인페이지 바텀시트 내부 키워드선택 레이아웃 수정
  src/components/HomePage/BottomSheet/BottomSheetContent.stories.tsx
  src/components/HomePage/BottomSheet/BottomSheetContent.tsx
  src/components/HomePage/BottomSheet/KeywordContainer.tsx
  src/components/HomePage/BottomSheetContent/BottomSheetContent.tsx
  src/pages/Home/HomePage.tsx
Labels: ♻️ refactor, 🎨style

#227 feat : 지도 편지 페이지 숨길 위치 모달 레이아웃
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
Labels: ✨feature

#226 feat : 로그인&회원가입 (4차) - 회원가입 페이지 수정
  src/components/Common/Input/Input.tsx
  src/components/RegisterPage/NicknameSection.tsx
  src/constants/authInputValidation.ts
  src/hooks/useRegisterForm.tsx
  src/service/auth/checkNickname.ts
  src/service/auth/register.ts
  src/service/auth/sendEmail.ts
  src/service/auth/verifyEmail.ts
  src/types/apiResponse.ts
  src/types/register.ts
Labels: ✏️chore, 🐛 fix, ♻️ refactor

#232 refactor : 편지 숨길 위치 zustand로 관리
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/hooks/useNominatimSearch.ts
  src/pages/Map/MapExplorerPage.tsx
  src/stores/useSearchStore.ts
Labels: ♻️ refactor

#228 refactor : 아이템 선택 페이지 리펙토링
  src/components/Common/TextArea/TextArea.tsx
  src/components/CreatLetterPage/LettetInputForm/LettetInputForm.tsx
  src/components/CreatLetterPage/Post/PostLetterForm.tsx
  src/components/CreatLetterPage/PostLetterCotainer/PostLetterCotainer.tsx
  src/components/SelectItemPage/AnimationBottle/AnimationBottle.stories.tsx
  src/components/SelectItemPage/AnimationBottle/AnimationBottle.tsx
  src/components/SelectItemPage/CreateButton/CreateButton.stories.tsx
  src/components/SelectItemPage/CreateButton/CreateButton.tsx
  src/components/SelectItemPage/ItemGroup/ItemGroup.tsx
  src/components/SelectItemPage/KeywordList/KeywordList.tsx
  src/components/SelectItemPage/LabelList/LabelList.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.stories.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.tsx
  src/components/SelectItemPage/SelectSlider/SelectSlider.tsx
  src/components/SelectItemPage/SelectToggle/SelectToggle.tsx
  src/components/SuccessLetterPage/SuccessModal/SuccessModal.stories.tsx
  src/components/SuccessLetterPage/SuccessModal/SuccessModal.tsx
  src/hooks/index.ts
  src/hooks/useAutoSave.ts
  src/hooks/useModal.tsx
  src/pages/Letter/Create/CreateLetterPage.tsx
  src/pages/Letter/SelectItem/SelectItemPage.tsx
  src/pages/Letter/Success/SuccessLetterPage.tsx
  src/pages/User/MyPage/MyPage.tsx
Labels: ✨feature

#236 fix : WelcomeMessageContainer 스토리북 수정
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.stories.tsx
Labels: 🐛 fix

#237 refactor : maplibre 컴포넌트 custom hook 분리
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/hooks/useCurrentLocation.ts
  src/hooks/useNearbyLetters.ts
Labels: ♻️ refactor

#239 feat: 지도 편지 페이지 최근 검색어 클릭 시 검색 기능
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/components/MapPage/SearchHistoryList/SearchHistoryList.tsx
Labels: ✨feature

#240 feat : 편지 보관함 페이지 레이아웃 작성
  src/components/StoragePage/StorageList.tsx
  src/pages/Storage/StoragePage.tsx
  src/pages/User/MyPage/MyPage.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨feature, 🎨style

#244 feat: 지도 편지 페이지 검색 자동완성 기능 구현 완료
  src/components/MapPage/RelatedSearchTermsList/RelatedSearchTermsList.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/hooks/useNominatimSearch.ts
  src/stores/useSearchStore.ts
Labels: ✨feature

#246 feat : 편지 상세 보기 페이지 신고하기 버튼, 모달 레이아웃
  src/components/LetterDetailPage/Report/ReportButton.tsx
  src/components/LetterDetailPage/Report/ReportModal.stories.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
  src/pages/Letter/Detail/LetterDetailPage.tsx
Labels: ✨feature

#248 feat : 라벨뽑기 페이지 수정
  public/라벨_샘플_01.png
  public/라벨_샘플_02.png
  src/components/Common/TitleClosedTopBar/TitleClosedTopBar.stories.tsx
  src/components/Common/TitleClosedTopBar/TitleClosedTopBar.tsx
  src/components/LabelLotteryPage/LotteryAnimationContainer.stories.tsx
  src/components/LabelLotteryPage/LotteryAnimationContainer.tsx
  src/components/NotificationPage/NotificationAppBar.tsx
  src/pages/Label/Lottery/LabelLotteryPage.tsx
  src/pages/Notification/NotificationPage.tsx
  src/router.tsx
Labels: ✨feature

#252 feat : 라벨뽑기 결과 모달 컴포넌트 개발 및 캔버스 캡처
  package.json
  public/꽝.svg
  src/components/Common/Modal/Modal.tsx
  src/components/Common/TitleClosedTopBar/TitleClosedTopBar.tsx
  src/components/LabelLotteryPage/ResultModalContainer.stories.tsx
  src/components/LabelLotteryPage/ResultModalContainer.tsx
  src/hooks/index.ts
  src/hooks/useDownloadCanvas.ts
  src/pages/Label/Lottery/LabelLotteryPage.tsx
  yarn.lock
Labels: ✨feature

#251 feat: 지도 페이지에서 숨길 장소 없을 경우 편지 작성 버튼 비활성화
  src/pages/Map/MapExplorerPage.tsx
Labels: ✨feature

#257 feat : 편지 보관함 페이지 작성
  .pnp.cjs
  src/components/Common/BottleLetter/Bottle/Bottle.tsx
  src/components/Common/BottleLetter/BottleLetter.tsx
  src/components/Common/BottleLetter/Label/Label.tsx
  src/components/Common/Itembox/Itembox.tsx
  src/components/SelectItemPage/KeywordList/KeywordList.tsx
  src/components/StoragePage/StorageList.tsx
  src/pages/Storage/StoragePage.tsx
  src/pages/User/MyPage/MyPage.stories.tsx
  src/service/storage/getLetter.ts
Labels: ✨feature

#260 fix : 빌드 오류 수정
  src/components/Profile/NicknameSection.tsx
  src/components/StoragePage/Storage.stories.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers/LoginHandler.ts
  src/mocks/handlers/RegisterHandler.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/userEditHandler.ts
  src/mocks/index.ts
  src/pages/Storage/StoragePage.stories.tsx
  src/pages/User/MyPage/MyPage.stories.tsx
  src/service/api.ts
  src/service/auth/refreshAccessToken.ts
Labels: 🐛 fix

#263 env : 배포 url 추가
  .github/workflows/deploy.yml
  .pnp.cjs
  package.json
  src/components/Common/BottleLetter/Label/Label.tsx
  src/mocks/browser.ts
  src/mocks/handlers/LoginHandler.ts
  src/mocks/handlers/RegisterHandler.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/userEditHandler.ts
  src/mocks/index.ts
Labels: 🔧env

#266 chore : 배포 이미지 경로 수정
  src/components/Common/BottleLetter/Label/Label.tsx
  src/components/CreatLetterPage/LettetInputForm/LettetInputForm.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.tsx
  src/index.css
Labels: ✏️chore, 🎨style

#267 feat : 로그인 페이지 리팩토링
  .pnp.cjs
  src/hooks/useLogin.ts
  src/pages/User/Login/LoginPage.tsx
  src/service/api.ts
  src/service/auth/login.ts
  src/service/auth/logout.ts
Labels: ✨feature, ♻️ refactor

#273 feat : 메인페이지 유저정보 연결
  src/components/HomePage/BottomSheet/BottomSheetContent.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.tsx
  src/pages/Home/HomePage.tsx
  src/service/storage/getRecentRely.ts
  src/stores/index.ts
  src/types/letter.ts
Labels: ✨feature

#271 refacotor : 키워드 편지 상세 조회 api 연동refactoring
  src/components/LetterDetailPage/DeleteButton/DeleteButton.stories.tsx
  src/components/LetterDetailPage/DeleteButton/DeleteButton.tsx
  src/components/LetterDetailPage/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/ReplyLetterDetail.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
  src/pages/Letter/Detail/LetterDetailPage.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
Labels: ♻️ refactor

#275 253 feat 지도 편지 페이지 주변 편지 조회 api 연동
  .pnp.cjs
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/hooks/useNearbyLetters.ts
  src/pages/Map/MapExplorerPage.tsx
  src/service/MapLetter/getNearbyLetters.ts
  src/stores/useSelectedLetterStore.tsx
  src/types/letter.ts
  src/util/calculateDaysLeft.ts
  src/util/formatDistance.ts
Labels: ✨feature

#280 chore : 키워드 상세 조회 페이지 타입 다시 추가
  src/types/letter.ts
Labels: ✏️chore

#281 feat : 메인페이지 bottom sheet 키워드 api 연동
  src/components/HomePage/BottomSheet/BottomSheetContent.tsx
  src/components/HomePage/BottomSheet/KeywordContainer.tsx
  src/hooks/useCreateUserKeywords.ts
  src/hooks/useGetAllKeywords.ts
  src/hooks/useGetUserKeywords.ts
  src/service/keyword/createUserKeyword.ts
  src/service/keyword/getAllKeyword.ts
  src/service/keyword/getUserKeyword.ts
Labels: ✨feature

#286 feat : 프로필 닉네임 갱신 / 프로필사진 변경 기능 api 연동
  src/components/Common/ProfileImage/ProfileImage.tsx
  src/components/Profile/NicknameSection.tsx
  src/components/Profile/ProfileImageSection.tsx
  src/hooks/useUserInfo.ts
  src/service/api.ts
  src/service/auth/refreshAccessToken.ts
  src/service/user/changeNickname.ts
  src/service/user/changeProfileImage.ts
  src/service/user/getUserInfo.ts
Labels: ✨feature, 🐛 fix

#291 feat : 메인페이지 추천/답장 편지 api 연동
  public/유리병.svg
  public/편지없음.svg
  src/components/Common/BottleLetter/Bottle/Bottle.tsx
  src/components/Common/Toggle/Toggle.tsx
  src/components/HomePage/HomeBottleLetter.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/hooks/useGetRecentRelyLetter.ts
  src/hooks/useGetRecommendLetter.ts
  src/pages/Home/HomePage.tsx
  src/service/storage/getRecentRely.ts
  src/service/storage/getRecommendedLetter.ts
  src/types/letter.ts
Labels: ✨feature, 🎨style

#287 276 feat 지도 편지 페이지 상세조회 api 연동
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.stories.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.stories.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/hooks/useGetNearbyLettersDetail.ts
  src/pages/Map/MapExplorerPage.tsx
  src/service/MapLetter/getNearByLetterDetail.ts
  src/types/letter.ts
Labels: ✨feature

#289 feat :키워드-지도 답장 편지 상세조회 api 연동
  src/components/LetterDetailPage/LetterDatail/ReplyLetterDetail.tsx
  src/hooks/useGetKeywordReplyLetterDetail.ts
  src/hooks/useGetMapReplyLetterDetail.ts
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
  src/router.tsx
  src/service/MapLetter/getMapReplyLetterDetail.ts
  src/service/detail/getKeywordReplyLetterDetail.ts
  src/types/letter.ts
Labels: ✨feature

#297 chore : 키워드 지도 편지 상세조회 페이지 수정
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
  src/router.tsx
  src/types/letter.ts
Labels: ✏️chore

#294 feat : api를 이용해 keyword 불러오기
  src/components/Common/TopBar/TopBar.stories.tsx
  src/components/CreatLetterPage/PostLetterCotainer/PostLetterCotainer.tsx
  src/components/HomePage/LetterContainer/LetterContainer.stories.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
  src/components/SelectItemPage/ItemGroup/ItemGroup.tsx
  src/components/SelectItemPage/KeywordList/KeywordList.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.tsx
  src/service/api.ts
  src/service/keyword/getAllKeyword.ts
  src/types/keyword.ts
Labels: ✨feature

#300 chore : 지도 편지 상세 페이지 표시되는 위치와 확대/축소 상태 관리 훅으로 분리
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/hooks/useLocationState.ts
Labels: ✏️chore

#290 feat : 라벨첩 페이지 레이아웃 + 전체 레이아웃 수정
  src/components/Common/BottleLetter/Label/Label.tsx
  src/components/Common/Container/Container.tsx
  src/components/Common/Input/NicknameInput.tsx
  src/components/Common/Itembox/Itembox.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/HomePage/TopButtonContainer/TopButtonContainer.tsx
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.tsx
  src/components/Profile/NicknameSection.tsx
  src/components/Profile/ProfileImageSection.tsx
  src/hooks/useUserInfo.ts
  src/index.css
  src/main.tsx
  src/pages/Home/HomePage.tsx
  src/pages/LabelCollectionsPage.tsx
  src/pages/Notification/NotificationPage.tsx
  src/pages/Storage/LabelCollectionsPage.tsx
  src/pages/User/Login/LoginPage.tsx
  src/pages/User/MyPage/MyPage.tsx
  src/pages/User/Profile/ProfilePage.tsx
  src/pages/User/Register/RegisterPage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/service/api.ts
  src/service/label/get/getUserLabel.ts
  src/service/user/changeNickname.ts
  src/types/label.ts
Labels: ✨feature, 🎨style

#306 fix : 머지 충돌 수정
  src/pages/Home/HomePage.tsx
Labels: 🐛 fix

#308 feat : 비밀번호 변경 로직 추가 & 빌드 오류 수정
  src/components/Common/Container/Container.tsx
  src/components/Common/Input/NicknameInput.tsx
  src/components/Common/Input/PasswordInput.tsx
  src/components/Common/Itembox/Itembox.tsx
  src/components/Common/ProfileImage/ProfileImage.stories.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
  src/components/Profile/AccountInfoSection.tsx
  src/components/Profile/NicknameSection.tsx
  src/components/Profile/ProfileImageSection.tsx
  src/hooks/useLogin.ts
  src/pages/Storage/LabelCollectionsPage.tsx
  src/pages/User/Profile/ProfilePage.tsx
  src/service/api.ts
  src/service/label/get/getUserLabel.ts
  src/service/user/changeNickname.ts
  src/service/user/changePassword.ts
  src/service/user/changeProfileImage.ts
  src/service/user/getUserInfo.ts
  src/types/profileImage.ts
Labels: ✏️chore, ✨feature

#307 chore : 지도 편지 상제 페이지 변경
  src/components/Common/DayCounter/DayCounter.stories.tsx
  src/components/Common/DayCounter/DayCounter.tsx
  src/components/LetterDetailPage/Keyword/KeywordList.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
  src/components/LetterDetailPage/LetterDetailContainer/KeywordLetterDetailContainer/KeywordLetterDetailContainer.tsx
  src/components/LetterDetailPage/LetterDetailContainer/MapLetterArchieveDetailContainer/MapLetterArchieveDetailContainer.tsx
  src/components/LetterDetailPage/LetterDetailContainer/MapLetterDetailContainer/MapLetterDetailContainer.tsx
  src/hooks/index.ts
  src/hooks/useGetArchivedLetter.ts
  src/hooks/useGetNearbyLettersDetail.ts
  src/index.css
  src/pages/Letter/Detail/KeywordLetterDetailPage/KeywordLetterDetailPage.tsx
  src/pages/Letter/Detail/LetterDetailPage.stories.tsx
  src/pages/Letter/Detail/MapLetterArchieveDetailContainerPage/MapLetterArchieveDetailContainerPage.tsx
  src/pages/Letter/Detail/MapLetterDetailPage/MapLetterDetailPage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/service/MapLetter/getArchivedLetter.ts
  src/service/MapLetter/getNearByLetterDetail.ts
  src/types/letter.ts
Labels: ✏️chore

#311 feat : 키워드 편지 상세 조회 삭제 기능 api 연동
  src/components/LetterDetailPage/Delete/DeleteButton.tsx
  src/components/LetterDetailPage/Delete/DeleteModal.stories.tsx
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useDeleteKeywordLetterReplyKeywordLetter.ts
  src/router.tsx
  src/service/detail/deleteKeywordLetterReplyKeywordLetter.ts
Labels: ✨feature

#315 feat : 키워드 편지 상세 조회 답장 리스트 api 연동
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/ReplyList/ReplyList.tsx
  src/hooks/useGetKeywordReplyList.ts
  src/router.tsx
  src/service/keyword/getKeywordReplyList.ts
  src/types/letter.ts
Labels: ✨feature

#317 feat : 리퀘스트 대기 요청 추가
  src/service/api.ts
  src/service/auth/refreshAccessToken.ts
Labels: ✨feature

#310 feat : 프로필 이미지 공유 페이지 추가
  src/components/MyPage/KeywordListSection.tsx
  src/pages/User/MyPage/MyPage.tsx
  src/pages/User/Profile/ProfileSharePage.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✨feature

#318 fix : 빌드 에러 수정
  .github/workflows/check.yml
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/ReplyList/ReplyList.stories.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/Maplibre/Maplibre.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
Labels: 🐛 fix

#319 feat : 지도 편지 상세 조회 답장 리스트 api 연동
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/ReplyList/ReplyList.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/Maplibre/Maplibre.stories.tsx
  src/components/MapPage/Maplibre/Maplibre.tsx
  src/hooks/useGetKeywordReplyList.ts
  src/hooks/useGetMapReplyList.ts
  src/service/MapLetter/getMapReplyList.ts
  src/service/detail/getKeywordLetterDetail.ts
  src/service/keyword/getKeywordReplyList.ts
  src/types/letter.ts
Labels: ✨feature

#322 321 chore 키워드 편지 상세 조회 삭제 요청 파라미터 수정
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/hooks/useDeleteKeywordLetter.ts
  src/hooks/useDeleteKeywordLetterReplyKeywordLetter.ts
  src/service/detail/deleteKeywordLetter.ts
Labels: ✏️chore

#329 style : 지도 편지 페이지 스타일 수정
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/pages/Map/MapExplorerPage.tsx
Labels: 🎨style

#330 style : 라벨첩 스타일 및 링크 연결
  src/components/Common/Itembox/Itembox.tsx
  src/hooks/useModal.tsx
  src/pages/Storage/LabelCollectionsPage.tsx
Labels: 🎨style

#327 feat : 지도 편지 주변 편지 상세보기 페이지 보관 api 연동
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
  src/hooks/usePostNearByLetterStorage.ts
  src/service/MapLetter/getNearByLetterDetail.ts
  src/service/MapLetter/postNearbyLettersStorage.ts
Labels: ✨feature

#334 feat : 키워드 편지 사용자가 보낸 답장 편지 상세 조회 api연동
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDetailContainer/KeywordLetterDetailContainer/KeywordLetterDetailContainer.tsx
  src/components/StoragePage/StorageList.tsx
  src/router.tsx
Labels: ✨feature

#335 feat : fcm 연동
  .github/workflows/check.yml
  .pnp.cjs
  package.json
  public/firebase-messaging-sw.js
  src/components/Common/ItemSlider/ItemSlider.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/CreatLetterPage/LetterInputForm/LetterInputForm.tsx
  src/components/CreatLetterPage/PostLetterCotainer/PostLetterCotainer.tsx
  src/components/HomePage/TopButtonContainer/TopButtonContainer.tsx
  src/components/SelectItemPage/AnimationBottle/AnimationBottle.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.tsx
  src/components/SelectItemPage/SelectSlider/SelectSlider.tsx
  src/components/SuccessLetterPage/SuccessModal/SuccessModal.tsx
  src/hooks/useCreateLetter.ts
  src/hooks/usePushNotification .ts
  src/pages/Home/HomePage.tsx
  src/pages/Letter/SelectItem/SelectItemPage.tsx
  src/router.tsx
  src/service/nofication/postToken.ts
  src/types/subscirbe.ts
  src/util/firebase.ts
  yarn.lock
Labels: ✨feature

#337 feat : 지도 편지 페이지 -주변 편지 API refetchinterval 옵션 추가
  src/hooks/useNearbyLetters.ts
Labels: ✨feature

#339 style : 에러 페이지 스타일링
  src/pages/ErrorPage.tsx
Labels: 🎨style

#341 style : 지도 페이지 스타일 수정
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
Labels: 🎨style

#343 feat : 랜덤 키워드 편지 신고 api 연동
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/Report/ReportButton.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
  src/hooks/usePostReportKeywordLetter.ts
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
  src/service/Report/postReportKeywordLetter.ts
  src/types/report.ts
Labels: ✨feature

#344 feat : 보관함 쿼리 적용 무한스크롤 설정
  .pnp.cjs
  package.json
  src/components/StoragePage/StorageList.tsx
  src/hooks/useInfiniteStorageFetch.ts
  src/pages/Storage/StoragePage.tsx
  yarn.lock
Labels: ✨feature

#347 chore : 지도 편지 경로 수정
  src/components/StoragePage/StorageList.tsx
Labels: ✏️chore

#351 fix : 이메일 인증 오류 처리
  src/hooks/useRegisterForm.tsx
  src/service/api.ts
  src/service/auth/verifyEmail.ts
  src/types/register.ts
Labels: 🐛 fix

#352 feat : 지도 편지 신고 API 연동
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
  src/hooks/usePostReportMapLetter.ts
  src/service/Report/postReportMapLetter.ts
Labels: ✨feature

#354 feat : 지도 답장 편지 신고 API 연동
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
  src/hooks/usePostReportMapReplyLetter.ts
  src/service/Report/postReportMapReplyLetter.ts
Labels: ✨feature

#358 chore : 편지 상세 textare 수정
  .github/workflows/deploy.yml
  src/components/Common/TextArea/TextArea.tsx
  src/hooks/usePushNotification .ts
Labels: ✏️chore

#359 feat : 알림페이지 api 연동 및 알림 타입 변경
  src/components/NotificationPage/NotificationContainer.tsx
  src/components/NotificationPage/NotificationItem.tsx
  src/hooks/useGetNotifications.ts
  src/hooks/useUpdateNotifications.ts
  src/pages/Notification/NotificationPage.tsx
  src/service/notification/getNotifiations.ts
  src/service/notification/updateNotificationStatus.ts
  src/types/notification.ts
Labels: ✨feature

#361 chore : nofication 제거
  src/pages/Home/HomePage.tsx
Labels: 🔧env

#362 chore : 빌드 수정
  .github/workflows/deploy.yml
  .pnp.cjs
  public/firebase-messaging-sw.js
Labels: 🐛 fix

#364 chore : 사용하지 않는 lockfile 명령어 제거
  .github/workflows/deploy.yml
Labels: 🔧env

#365 fix : manifest 오류 수정
  public/firebase-messaging-sw.js
  public/icon-192x192.svg
  public/icon-512x512.svg
  src/pages/Home/HomePage.tsx
  vite.config.ts
Labels: ✏️chore

#366 feat : 지도 답장 편지 삭제 api 연동 완료
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/hooks/useDeleteMapReceivedtLetter.ts
  src/service/MapLetter/deleteMapReceivedtLetter.ts
Labels: ✨feature

#369 feat : 지도 편지 답장 확인 API연동
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
  src/hooks/useGetCheckMapReplyLetter.ts
  src/service/MapLetter/getCheckMapReplyLetter.ts
Labels: ✨feature

#372 fix : 잘못 연결된 보관함 경로 수정
  src/components/Common/Banner/LabelLotteryBanner.tsx
  src/components/Common/Container/Container.tsx
  src/components/StoragePage/StorageList.tsx
  src/pages/Storage/StoragePage.tsx
  src/router.tsx
Labels: 🐛 fix

#373 chore : fcm 오류 제거
  src/util/firebase.ts
Labels: ✏️chore

#379 fix : api 호출이 안 가는 에러 수정
  .github/workflows/deploy.yml
  .pnp.cjs
  index.html
  package.json
  public/manifest.json
  public/mockServiceWorker.js
  src/App.tsx
  src/pages/Home/HomePage.tsx
  src/pages/User/Login/LoginPage.tsx
  vite.config.ts
  yarn.lock
Labels: 🐛 fix

#381 feat : 알림페이지 라우팅 경로 수정 및 알림이 없을 때 보여줄 컴포넌트 생성
  src/components/HomePage/HomeBottleLetter.tsx
  src/components/NotificationPage/NotificationItem.tsx
  src/components/NotificationPage/ZeroNotification.tsx
  src/pages/Notification/NotificationPage.tsx
Labels: ✨feature

#383 chore : 편지 상세 페이지 라벨 표시
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
Labels: ✏️chore, 🎨style

#385 chore : 수정사항 반영
  public/kakao_login_medium_wide.png
  public/배너샘플1.png
  public/배너샘플2.png
  public/배너샘플3.png
  src/components/Common/Banner/ArchivedlBanner.tsx
  src/components/Common/Banner/Banner.tsx
  src/components/Common/Banner/LabelCollectionsBanner.tsx
  src/components/Common/BannerContainer/BannerContainer.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Storage/StoragePage.tsx
  src/pages/User/Login/KakaoRedirectPage.tsx
  src/pages/User/Login/LoginPage.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: ✏️chore

#388 chore : 지도 편지 작성 url 추가 및 수정
  src/pages/Map/MapExplorerPage.tsx
  src/router.tsx
Labels: ✏️chore

#389 style : 검색 결과 없을 때 스타일 수정
  src/pages/Map/MapExplorerPage.tsx
Labels: 🎨style

#393 style : 배너 스타일 깨짐 수정
  src/components/Common/BackButtonContainer/BackButtonCotainer.tsx
  src/components/Common/Banner/Banner.tsx
  src/components/Common/Container/Container.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/MapPage/NavigateContainer/NavigateContainer.tsx
  src/pages/Map/MapExplorerPage.tsx
  src/pages/Storage/StoragePage.tsx
  src/pages/User/Profile/ProfilePage.tsx
  src/router.tsx
Labels: 🎨style

#395 feat : 지도 편지 작성
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/TextArea/TextArea.tsx
  src/components/CreatLetterPage/LetterInputForm/LetterInputForm.tsx
  src/components/CreatLetterPage/PostLetterCotainer/PostLetterCotainer.tsx
  src/components/CreateMapLetter/CreateMapLetterCotainer/CreateMapLetterCotainer.tsx
  src/hooks/useCreateMapLetter.ts
  src/hooks/usePushNotification .ts
  src/pages/Map/Create/CreateMapLetterPage.tsx
  src/pages/Map/Select/MapSelectItemPage.tsx
  src/router.tsx
  src/service/letter/create/createMapLetter.ts
Labels: ✨feature

#396 chore : 설정 변경
  src/components/CreatLetterPage/PostLetterCotainer/PostLetterCotainer.tsx
  src/components/CreateMapLetter/CreateMapLetterCotainer/CreateMapLetterCotainer.tsx
  src/pages/Map/MapExplorerPage.tsx
Labels: ✨feature

#397 chore : nofication hook 제거
  src/App.tsx
Labels: ✏️chore

#398 chore : 편지 상세 보기 페이지 답장하기 버튼 수정
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/LetterDatail/ReplyLetterDetail.tsx
  src/components/LetterDetailPage/ReplyList/ReplyList.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
Labels: ✏️chore

#399 feat : 스토리지 누락된 삭제 기능 추가
  public/라벨_샘플_1.png
  public/라벨_샘플_2.png
  public/라벨_샘플_3.png
  public/라벨_샘플_4.png
  public/라벨_샘플_5.png
  public/라벨_샘플_6.png
  src/components/Common/BackButtonContainer/BackButtonCotainer.tsx
  src/components/Common/Container/Container.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useModal.tsx
  src/pages/Storage/LabelCollectionsPage.tsx
  src/pages/Storage/StoragePage.tsx
  src/service/letter/delete/deleteLetters.ts
Labels: ✨feature

#402 chore : 버튼, 스타일, 링크 관련 수정
  src/components/RegisterPage/EmailSection.tsx
  src/components/RegisterPage/NicknameSection.tsx
  src/hooks/useRegisterForm.tsx
  src/pages/User/Login/LoginPage.tsx
  src/pages/User/Register/RegisterPage.tsx
Labels: ✏️chore

#403 chore : 기타 누락사항 추가
  src/pages/User/Register/RegisterPage.tsx
Labels: ✏️chore

#410 style : 지도 마커 스타일링
  public/placeMarker.svg
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/MapPage/Maplibre/map_style.json
  tailwind.config.js
Labels: 🎨style

#412 style : 플로팅 버튼 스타일 변경
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  tailwind.config.js
Labels: 🎨style

#414 chore : 키워드, 지도 편지 수정
  src/components/Common/NotificationBadge/NotificationBadge.stories.tsx
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/ReplyLetterDetail.tsx
  src/components/LetterDetailPage/LetterDetailContainer/KeywordLetterDetailContainer/KeywordLetterDetailContainer.tsx
  src/components/LetterDetailPage/LetterDetailContainer/MapLetterArchieveDetailContainer/MapLetterArchieveDetailContainer.tsx
  src/components/LetterDetailPage/Report/ReportModal.stories.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/NotificationPage/NotificationItem.stories.tsx
  src/hooks/useGetArchivedLetter.ts
  src/pages/Letter/Detail/MapLetterArchieveDetailContainerPage/MapLetterArchieveDetailContainerPage.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.stories.tsx
  src/pages/Letter/Detail/ReplyLetterDetailPage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/service/MapLetter/getArchivedLetter.ts
  src/types/letter.ts
Labels: ✏️chore, 🐛 fix

#417 style : 메인페이지
  public/무인도.svg
  public/물결.svg
  public/홈_유리병.svg
  src/components/Common/Container/Container.tsx
  src/components/HomePage/HomeBottle.tsx
  src/components/HomePage/HomeBottleLetter.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.tsx
  src/index.css
  src/pages/Home/HomePage.tsx
Labels: 🎨style

#419 chore : 알림버튼 z-index 수정
  src/components/HomePage/LetterContainer/LetterContainer.tsx
Labels: ✏️chore

#422 style : 모달 버튼 지도 디자인 수정
  src/components/Common/TopBar/TopBar.tsx
  src/components/HomePage/BottomSheet/BottomSheetContent.tsx
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/components/LetterDetailPage/LetterDetailContainer/KeywordLetterDetailContainer/KeywordLetterDetailContainer.tsx
  src/components/LetterDetailPage/LetterDetailContainer/MapLetterArchieveDetailContainer/MapLetterArchieveDetailContainer.tsx
  src/components/LetterDetailPage/LetterDetailContainer/MapLetterDetailContainer/MapLetterDetailContainer.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/NavigateContainer/NavigateContainer.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Map/MapExplorerPage.tsx
  src/pages/Notification/NotificationPage.tsx
Labels: ✏️chore, 🎨style

#423 chore : 보관함 url 연결
  index.html
  src/components/StoragePage/StorageList.tsx
  src/hooks/useInfiniteStorageFetch.ts
  src/index.css
Labels: ✏️chore

#425 style : 버튼 디자인 수정
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/LetterDatail/MapLetterDetail/MapLetterDetail.tsx
  src/pages/Map/MapExplorerPage.tsx
  tailwind.config.js
Labels: 🎨style

#433 chore : 보관함 경로 수정으로 인한 삭제 api 변경
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useDeleteMapArchivedLetter.ts
  src/service/MapLetter/deleteMapArchivedLetter.ts
Labels: ✏️chore

#438 fix : 지도 편지 상세보기 로딩 시간 단축
  src/components/LetterDetailPage/LetterDatail/MapLetterArchieveDetail/MapLetterArchieveDetail.tsx
  src/hooks/useGetMapReplyList.ts
Labels: 🐛 fix

#440 fix : 키워드 편지 상세보기 로딩 시간 단축
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
Labels: 🐛 fix

#442 design : BottleLetter 컴포넌트 css 수정
  public/라벨택_유리병.svg
  src/components/Common/BottleLetter/Bottle/Bottle.tsx
  src/components/Common/BottleLetter/BottleLetter.tsx
Labels: 🎨design

#436 env : Lighthouse cicd 적용
  .github/workflows/check.yml
  .github/workflows/deploy.yml
  .github/workflows/lighthouse.yml
  .gitignore
  .lighthouserc.cjs
  .pnp.cjs
  package.json
  yarn.lock
Labels: 🔧env

#443 refactor : 보관함 리팩토링
  src/components/StoragePage/LetterDateGroup.tsx
  src/components/StoragePage/LetterListItem.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useInfiniteStorageFetch.ts
  src/pages/Storage/StoragePage.tsx
  src/pages/User/MyPage/MyPage.tsx
  src/router.tsx
  src/types/letter.ts
Labels: ♻️ refactor

#448 design : 어플리케이션 레이아웃 디자인 수정
  src/components/Common/Container/Container.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/index.css
  src/pages/Map/MapExplorerPage.tsx
  src/pages/Storage/StoragePage.tsx
  src/router.tsx
Labels: 🎨design

#447 refactor : 편지 상세보기 페이지 신고 모달 리펙토링
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/LetterDetailPage/LetterDatail/KeywordLetterDetail/KeywordLetterDetail.tsx
  src/components/LetterDetailPage/Report/ReportModal.tsx
Labels: ♻️ refactor

#449 refactor : 일기 작성페이지 리펙토링
  .pnp.cjs
  .storybook/preview.jsx
  package.json
  public/편지지_샘플_1.png
  public/편지지_샘플_2.png
  public/편지지_샘플_3.png
  public/편지지_샘플_4.png
  public/편지지_샘플_5.png
  public/편지지_샘플_6.png
  src/App.tsx
  src/ErrorBoundary.tsx
  src/asset/letter1/bottom_cloud.svg
  src/asset/letter1/letter1.svg
  src/asset/letter1/top_cloud.svg
  src/asset/letter2/letter2.svg
  src/asset/letter2/letter_bg2_left.2c25d20b.svg
  src/asset/letter2/letter_bg2_right.4315fa8b.svg
  src/asset/letter3/bg1_mobile.99e45830.svg
  src/asset/letter3/bg2_mobile.16ef09f6.svg
  src/asset/letter3/letter3.svg
  src/asset/line.svg
  src/components/Common/BackButton/BackButton.tsx
  src/components/Common/ItemSlider/ItemSlider.stories.tsx
  src/components/Common/ItemSlider/ItemSlider.tsx
  src/components/Common/TextArea/TextArea.tsx
  src/components/Common/TopBar/TopBar.stories.tsx
  src/components/Common/TopBar/TopBar.tsx
  src/components/Common/usePushNotification.tsx
  src/components/CreatLetterPage/LetterForm/LetterForm.tsx
  src/components/CreatLetterPage/LetterInput/LetterInput.tsx
  src/components/CreatLetterPage/LetterInputForm/LetterInputForm.tsx
  src/components/CreatLetterPage/LetterLine/LetterLine.tsx
  src/components/CreatLetterPage/PostLetterContainer/PostLetterContainer.tsx
  src/components/CreatLetterPage/PostLetterCotainer/PostLetterCotainer.tsx
  src/components/CreatLetterPage/Theme/FlowerLetter/FlowerLetter.tsx
  src/components/CreatLetterPage/Theme/HeartLetter/HeartLetter.tsx
  src/components/CreatLetterPage/Theme/SkyLetter/SkyLetter.tsx
  src/components/CreatLetterPage/ThemeWrapper/ThemeWrapper.tsx
  src/components/SelectItemPage/SelectItem/SelectItem.tsx
  src/components/SelectItemPage/SelectSlider/SelectSlider.tsx
  src/hooks/index.ts
  src/hooks/useDraftLetter.ts
  src/hooks/useLetterDB.ts
  src/pages/Letter/Create/CreateLetterPage.tsx
  src/pages/Letter/SelectItem/SelectItemPage.tsx
  src/pages/Map/MapExplorerPage.stories.tsx
  src/pages/Map/MapExplorerPage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: ♻️ refactor

#455 refactor : 토글 컴포넌트 스타일 분리
  src/components/Common/Toggle/Toggle.stories.tsx
  src/components/Common/Toggle/Toggle.tsx
  src/components/Common/Toggle/constants.ts
  src/components/SelectItemPage/SelectSlider/SelectSlider.tsx
  src/pages/Home/HomePage.tsx
Labels: ♻️ refactor, 🎨design

#458 refactor : NotificationBadge 컴포넌트 수정
  src/components/Common/NotificationBadge/NotificationBadge.tsx
  src/components/Common/Toggle/Toggle.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/SelectItemPage/SelectSlider/SelectSlider.tsx
  src/constants/maxNotificationCount.ts
  src/constants/toggleVariant.ts
  src/pages/Home/HomePage.tsx
Labels: ♻️ refactor
