Repository prgrms-web-devcourse-final-project/WEB1_1_Postman_FE, pull requests merged in 2025-01, with the labels that each got.

#464 ci : 브랜치명 변경
  .gitattributes
  .github/workflows/check.yml
  .github/workflows/deploy.yml
  .github/workflows/lighthouse.yml
  .github/workflows/storybook.yml
  public/manifest.json
Labels: 🔧env

#462 refactor : 리스트 아이템 컴포넌트 수정&리팩토링
  src/assets/Location.svg
  src/assets/rightArrow.svg
  src/components/Common/LetterListItem/Category.tsx
  src/components/StoragePage/LetterDateGroup.tsx
  src/components/StoragePage/LetterListItem.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useInfiniteStorageFetch.ts
  src/pages/Storage/StoragePage.tsx
  src/router.tsx
  src/service/storage/getLetter.ts
  src/types/letter.ts
Labels: ♻️ refactor

#461 refactor : 지도 페이지 리팩토링
  src/components/LetterDetailPage/LetterDetailContainer/MapLetterArchieveDetailContainer/MapLetterArchieveDetailContainer.tsx
  src/components/MapPage/LetterInfoContainer/LetterInfoContainer.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/pages/Map/MapExplorerPage.tsx
Labels: ♻️ refactor

#465 design : 로그인&회원가입 페이지 스타일 변경
  public/sw.js
  src/components/RegisterPage/EmailSection.tsx
  src/pages/User/Login/LoginPage.tsx
  src/pages/User/Register/RegisterPage.tsx
Labels: 🎨design

#468 refactor: 일기 조회 페이지 리펙토링
  src/components/Common/TopBar/TopBar.stories.tsx
  src/components/CreateMapLetter/CreateMapLetterCotainer/CreateMapLetterCotainer.tsx
  src/hooks/useNearbyLetters.ts
  src/pages/Letter/SelectItem/SelectItemPage.tsx
  src/pages/Map/Select/MapSelectItemPage.tsx
Labels: ♻️ refactor

#466 refactor : 메인페이지 리팩토링 및 레이아웃 수정
  public/물결.svg
  src/components/Common/Container/Container.tsx
  src/components/Common/GradientContainer/GradientContainer.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/WaveContainer/WaveContainer.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/hooks/useGetThreeLetterData.ts
  src/hooks/usePushNotifications.ts
  src/pages/Home/HomePage.tsx
  src/router.tsx
Labels: ♻️ refactor

#472 refactor : 메인페이지 물병 컴포넌트
  public/홈_유리병.svg
  src/components/Common/WaveContainer/WaveContainer.tsx
  src/components/HomePage/HomeBottle.tsx
  src/components/HomePage/HomeBottleLetter.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/index.css
  src/pages/Home/HomePage.tsx
Labels: ♻️ refactor, 🎨design

#476 refactor : 메인페이지 추가 개발
  public/무인도.svg
  public/물결.svg
  public/편지없음.svg
  src/assets/bottle/bottle_daytime.svg
  src/assets/bottle/bottle_midnight.svg
  src/assets/bottle/bottle_nightfall.svg
  src/assets/bottle/index.ts
  src/assets/island/index.ts
  src/assets/island/island_daytime.svg
  src/assets/island/island_midnight.svg
  src/assets/island/island_nightfall.svg
  src/assets/wave/index.ts
  src/assets/wave/wave_daytime.svg
  src/assets/wave/wave_midnight.svg
  src/assets/wave/wave_nightfall.svg
  src/components/Common/GradientContainer/GradientContainer.tsx
  src/components/Common/LogoContainer/Logo.tsx
  src/components/Common/WaveContainer/WaveContainer.tsx
  src/components/HomePage/BottomSheet/BottomSheetContent.tsx
  src/components/HomePage/HomeBottle.tsx
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/HomePage/TopButtonContainer/TopButtonContainer.tsx
  src/components/HomePage/WelcomeMessageContainer/WelcomeMessageContainer.tsx
  src/hooks/useTimeOfDay.ts
  src/pages/Home/HomePage.tsx
Labels: ✨feature, ♻️ refactor

#480 refactor : service api.ts
  src/service/api.ts
Labels: ♻️ refactor

#477 feat : 마커 겹침 방지 및 클러스터링 기능 추가
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
Labels: ✨feature

#481 fix : 브라우저 캐시때문에 이전의 버전을 브라우저에서 보여주던 문제 해결
  .github/workflows/deploy.yml
  public/sw.js
  vite.config.ts
Labels: 🐛 fix

#486 perf : react icons -> react icons all
  .pnp.cjs
  package.json
  src/components/Common/Input/Input.tsx
  src/components/Common/LetterLayout/LetterLayout.tsx
  src/components/Common/NavigationBar/NavigationBar.tsx
  src/components/Common/TitleBackTopBar/TitleBackTopBar.tsx
  src/components/Common/TitleClosedTopBar/TitleClosedTopBar.tsx
  src/components/Common/Toast/Toast.tsx
  src/components/CreatLetterPage/LetterLine/LetterLine.tsx
  src/components/CreatLetterPage/Theme/FlowerLetter/FlowerLetter.tsx
  src/components/CreatLetterPage/Theme/HeartLetter/HeartLetter.tsx
  src/components/HomePage/TopButtonContainer/TopButtonContainer.tsx
  src/components/LetterDetailPage/Keyword/KeywordList.tsx
  src/components/LetterDetailPage/Report/ReportButton.tsx
  src/components/MapPage/Maplibre/MaplibreWithSearch.tsx
  src/components/MapPage/RelatedSearchTermsList/RelatedSearchTermsList.tsx
  src/components/MapPage/SearchFullScreen/SearchFullScreen.tsx
  src/components/StoragePage/LetterListItem.tsx
  yarn.lock
Labels: 🐑perf

#490 fix : 동작하지 않는 키워드 받은 편지 답장 편지 수정
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
Labels: 🐛 fix
