Repository prgrms-web-devcourse-final-project/WEB1_1_Postman_FE, pull requests merged in 2025-02, with the labels that each got.

#493 feat : 보관함 삭제 기능 api 수정
  src/components/StoragePage/DeleteModal.tsx
  src/components/StoragePage/LetterDateGroup.tsx
  src/components/StoragePage/LetterListItem.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useGetKeywordLetterDetail.ts
  src/pages/Storage/StoragePage.tsx
  src/pages/User/Register/RegisterPage.tsx
  src/service/letter/delete/deleteBookmarkLetters.ts
  src/service/letter/delete/deleteKeywordLetters.ts
  src/service/letter/delete/deleteMapLetters.ts
  src/service/storage/getRecommendedLetter.ts
  src/types/letter.ts
Labels: ✨feature, 🐛 fix, ♻️ refactor

#495 feat : 지도 편지 답장, 보관하기 버튼 추가
  src/components/Common/LetterLayout/LetterLayout.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
Labels: ✨feature

#497 상세보기 페이지 답장 편지 리스트 추가
  src/components/Common/LetterLayout/LetterLayout.tsx
  src/components/LetterDetailPage/Delete/DeleteModal.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
  src/components/LetterDetailPage/ReplyList/ReplyList.tsx
  src/types/letter.ts
Labels: ✨feature

#499 fix : 답장 편지 연동 오류 해결
  src/components/Common/LetterLayout/LetterLayout.tsx
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
  src/components/SelectItemPage/SelectToggle/SelectToggle.tsx
  src/pages/Letter/Create/CreateLetterPage.tsx
  src/router.tsx
  src/service/letter/create/postKeywordReplyLetter.ts
  src/service/letter/create/postMapReplyLetter.ts
Labels: 🐛 fix

#500 fix : 보관함에서 편지 삭제 시 401 auth 에러가 발생하는 오류 해결
  src/components/HomePage/LetterContainer/LetterContainer.tsx
  src/components/StoragePage/StorageList.tsx
  src/hooks/useGetKeywordLetterDetail.ts
  src/service/letter/delete/deleteBookmarkLetters.ts
  src/service/letter/delete/deleteMapLetters.ts
  src/service/storage/getRecommendedLetter.ts
  src/types/letter.ts
Labels: ✨feature, 🐛 fix

#504 fix : 지도 편지페이지에서 지도편지 상세 조회시 답장 편지로 api가 전송되는 오류 해결
  src/components/LetterDetailPage/LetterDetailContainer/LetterDetailContainer.tsx
Labels: 🐛 fix

#505 feat : 라벨첩 api 연결
  src/pages/Storage/LabelCollectionsPage.tsx
  src/service/label/get/getUserLabel.ts
Labels: ✨feature

#508 지도 편지 이미지 깨지는 문제 해결
  index.html
  src/components/CreatLetterPage/LetterLine/LetterLine.tsx
  src/components/CreateMapLetter/CreateMapLetterCotainer/CreateMapLetterCotainer.tsx
  src/pages/Letter/Detail/LetterDetailPage.tsx
Labels: 🐛 fix
